# -*- coding: utf-8 -*-
"""movie-recommendor sysytem

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNPgZK73aQLJrAarqYqkvoC8jGoJOR8S
"""

import pandas as pd
import numpy as np

movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv("tmdb_5000_credits.csv")

movies.head(1)

credits.head(1)

movies = movies.merge(credits,on='title')

movies.head(2)

# Feature selection

movies.info()

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

movies.head()

movies.isnull().sum()

movies.dropna(inplace=True)

movies.isnull().sum()

movies.duplicated().sum()

movies.iloc[0].genres

import ast
def convert(obj):
  l=[]
  for i in ast.literal_eval(obj):
    l.append(i['name'])
  return l

movies['genres'] = movies['genres'].apply(convert)

movies.head()

movies['keywords'] = movies['keywords'].apply(convert)

movies.head(1)

def convert3(obj):
  l=[]
  count=0
  for i in ast.literal_eval(obj):
    if count!=3:
      l.append(i['name'])
      count+=1
    else:
      break
  return l

movies['cast'] = movies['cast'].apply(convert3)

movies.head(1)

def fetch_director(obj):
  l=[]
  count=0
  for i in ast.literal_eval(obj):
    if i['job'] == 'Director':
      l.append(i['name'])
      break
  return l

movies['crew'] = movies['crew'].apply(fetch_director)

movies.head(1)

movies['overview'] = movies['overview'].apply(lambda x:x.split())

movies.head(1)

movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']= movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']= movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['crew']= movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])

movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

new_df = movies[['movie_id','title','tags']]

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df.head(1)

new_df['tags'][0]

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df.head()

! pip install nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def  stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))

  return  " ".join(y)

new_df['tags'] = new_df['tags'].apply(stem)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors

len(cv.vocabulary_)

cv.vocabulary_

# distance is inversly realted to similarity

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors).shape

similariy = cosine_similarity(vectors)

list(enumerate(similariy[0]))

def recommend(movie):
  movie_index = new_df[new_df['title']==movie].index[0]
  distances = similariy[movie_index]
  movies_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
  for i in movies_list:
    print(new_df.iloc[i[0]].title)

recommend('Batman Begins')

new_df.iloc[1216].title

import pickle

pickle.dump(new_df,open('movies.pkl','wb'))



pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))

pickle.dump(similariy,open('similarity.pkl','wb'))